name: build and publish

on: [push]

env:
  VERSION: 0.1.${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        os: [linux]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: make
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
          CGO_ENABLED: 0
        run: |
          go mod vendor
          go test ./...
          go build -ldflags="-s -w -X main.Version=$VERSION" -a -o bin/$GOOS/$GOARCH/rdfoxcli main.go