name: build and publish

on: [push]

env:
  VERSION: 0.1.${{ github.sha }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: make
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/darwin/app
            bin/linux/app
            bin/windows/app.exe